# A sample Gemfile
source "https://rubygems.org"

gem 'ec2ssh'
gem 'git-pr-release', '0.6.0'

# termial
gem "tmuxinator"

# vim
gem "gem-ctags"
gem "gem-browse"

# reference
gem "refe2"
gem "bitclust-dev"
gem "bitclust-core"

# guard
gem 'guard'
gem 'guard-rspec'
gem 'guard-bundler'
gem 'terminal-notifier-guard'
gem 'spring'
gem 'spring-commands-rspec'
gem 'rb-fsevent'

# github page
# gem 'github-pages'
