---
- name: set fact for golang
  set_fact:
    golang:
      gopath: "{{ lookup('env', 'HOME') }}"

- name: brew install go
  homebrew: >
    name={{ item }}
    state=latest
    update_homebrew=yes
  with_items:
    - go

- name: go get
  # -uで常に最新
  shell: go get -u {{ item }}
  with_items: '{{ golang_get_repositories }}'
  environment:
    GOPATH: '{{ golang.gopath }}'

- name: place a profile file
  copy:
    dest: '{{ ansible_env.HOME }}/etc/profile.d/golang'
    content: |
      export GOPATH={{ golang.gopath }}
      export PATH=$PATH:$GOPATH/bin

