---
- name: brew install fish
  homebrew: >
    name=fish
    state=latest

- name: add /usr/local/bin/fish to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: /usr/local/bin/fish
  become: yes

- name: switch default shell
  shell: chsh -s /usr/local/bin/fish {{ ansible_user_id }}
  become: yes

- name: install plugin manager
  shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman

- name: install plugins
  shell: fisher install {{ item  }}
  args:
    executable: /usr/local/bin/fish
  with_items:
    - z

- name: update fisherman
  shell: fisher update
  args:
    executable: /usr/local/bin/fish
