---
- hosts: localhost
  roles:
    - role: home
      tags: home
      home:
        directories:
          - bin
          - tmp
          - etc/profile.d
          - swap
          - undo
          - backup
          - tags
          - src
          - .trash
          - .tmux
          - .config/fish/conf.d
        download_profiles:
          - https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh
        dotfiles:
          - gitignore
          - agignore
          - gitconfig
          - aliases
          - functions
          - commonprofile
          - bashrc
          - profile
          # - zsh
          # - zlogin
          # - zlogout
          # - zpreztorc
          # - zprofile
          # - zshenv
          # - zshrc
          # - zsh
          - ctags.d
          - my.cnf
          - pryrc
          - tigrc
          - tmux.conf
          - rspec
          - vim
          - vimrc
          - gvimrc
          - { name: Guardfile, hide: False }
          - alacritty.yml
    - role: brew
      tags: brew
      brew:
        repositories:
          - sanemat/font
        formulae:
          - git
          - git-lfs
          - hub
          - gibo
          - hg
          - wget
          - w3m
          - tig
          - ag
          - tmux
          - reattach-to-user-namespace
          - libevent
          - fontforge
          - bash-completion
          - openssl
          - coreutils
          - nodejs
          - memcached
          - redis
          - mysql
          - ctags
          - { name: universal-ctags/universal-ctags/universal-ctags, state: head }
          - automake
          - pkg-config
          - { name: ricty, install_options: 'powerline,vim-powerline' }
          - jq
          - ghq
          - direnv
          - peco
          - fd
          - pyenv
          - pyenv-virtualenv
    # - role: vim
    - role: source-highlight
      tags: source-highlight
    - role: awscli
      tags: awscli
    - role: fish
      tags: fish
    # - role: zsh
      # tags: zsh
    - role: dircolors
      tags: dircolors
    - role: php
      tags: php
    - role: ruby
      tags: ruby
      ruby_version: 2.5.0
    - role: golang
      tags:
        - golang
        - go
      golang_get_repositories:
        # - golang.org/x/tools/cmd/goimports
        # - golang.org/x/tools/cmd/cover
        # - golang.org/x/tools/cmd/godoc
        - golang.org/x/tools/cmd/...
        - github.com/golang/lint/golint
        - github.com/golang/lint
        - github.com/motemen/gore
        - github.com/nsf/gocode
        - github.com/k0kubun/pp
        - github.com/rogpeppe/godef
        - github.com/jstemmer/gotags
        - github.com/mattn/gom
        - github.com/b4b4r07/gist
    - role: vagrant
    - role: packer
    - role: workspace
      workspace_repositories:
        - violetyk/cake.vim
        - violetyk/cake3.vim
        - violetyk/scratch-utility
        - violetyk/w.vim
        - violetyk/neosnippet-cakephp2
        - violetyk/neosnippet-rails
        - violetyk/neosnippet-aws-cloud-formation
        - violetyk/neocomplete-php.vim
        - violetyk/iikanji-markdown.vim
        - violetyk/lab
        - violetyk/graid
        - mbadolato/iTerm2-Color-Schemes 
  post_tasks:
    - name: reload shell profile
      shell: exec $SHELL -l
      tags:
        # 常に実行する特殊タグ（--skip-tags alwaysでスキップ）
        - always
