---
- name: brew install awscli
  homebrew: >
    name=awscli
    state=latest

- name: place a exports file
  copy:
    dest: '{{ ansible_env.HOME }}/etc/profile.d/awscli'
    content: |
      export AWS_DEFAULT_REGION=ap-northeast-1
      export AWS_DEFAULT_OUTPUT=json # json or table or text
      export AWS_DEFAULT_PROFILE=dev
      export AWS_CONFIG_FILE=~/.aws/config
      export AWS_CREDENTIAL_FILE=~/.aws/credentials

- name: place a fish config
  copy:
    dest: '{{ ansible_env.HOME }}/.config/fish/conf.d/awscli.fish'
    content: |
      set -x AWS_DEFAULT_REGION ap-northeast-1
      set -x AWS_DEFAULT_OUTPUT json
      set -x AWS_DEFAULT_PROFILE dev
      set -x AWS_CONFIG_FILE ~/.aws/config
      set -x AWS_CREDENTIAL_FILE ~/.aws/credentials
