---
- name: brew install awscli
  homebrew: >
    name=awscli
    state=latest

- name: place a exports file
  copy:
    dest: '{{ ansible_env.HOME }}/etc/exports.d/awscli'
    content: |
      export AWS_DEFAULT_REGION=ap-northeast-1
      export AWS_DEFAULT_OUTPUT=json # json or table or text
      export AWS_DEFAULT_PROFILE=dev
      export AWS_CONFIG_FILE=~/.aws/config
      export AWS_CREDENTIAL_FILE=~/.aws/credentials
