---
- name: brew install coreutils
  homebrew: >
    name=coreutils
    state=latest

- name: git clone dircolors-solarized
  git: >
    repo=git@github.com:seebi/dircolors-solarized.git
    dest={{ lookup('env', 'HOME') }}/src/github.com/seebi/dircolors-solarized
    accept_hostkey=yes

- name: link color theme
  file: >
    src={{ lookup('env', 'HOME') }}/src/github.com/seebi/dircolors-solarized/dircolors.256dark
    dest={{ ansible_env.HOME }}/.dircolors
    state=link
    force=yes

- name: place a profile file
  copy:
    dest: '{{ ansible_env.HOME }}/etc/profile.d/dircolors'
    content: |
      if [ -f ~/.dircolors ]; then
        if type dircolors > /dev/null 2>&1; then
          eval $(dircolors ~/.dircolors)
        elif type gdircolors > /dev/null 2>&1; then
          eval $(gdircolors ~/.dircolors)
        fi
      fi

