---
- name: brew install source-highlight
  homebrew: >
    name=source-highlight
    state=latest

- name: place a profile file
  copy:
    dest: '{{ ansible_env.HOME }}/etc/profile.d/source-highlight'
    content: |
      if which source-highlight > /dev/null 2>&1; then
        export LESS='-iMR'
        export LESSOPEN='| {{ role_path }}/files/src-hilite-lesspipe.sh %s'
      fi
