#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# git-prompt.shの設定

# $()を展開する
setopt PROMPT_SUBST
# ステージ済みがある場合+、ステージしてない変更がある場合*を表示
# GIT_PS1_SHOWDIRTYSTATE=true
# stashがある場合$を表示
# GIT_PS1_SHOWSTASHSTATE=true
# untracked fileがある場合%を表示
# GIT_PS1_SHOWUNTRACKEDFILES=false
# アップストリームとの差分を< >で表示
GIT_PS1_SHOWUPSTREAM='auto'
# 特定のタグやブランチをチェックアウトしていたときの表示
GIT_PS1_DESCRIBE_STYLE='branch'
# 色つき表示
GIT_PS1_SHOWCOLORHINTS=true

# PROMPT上書き
export PROMPT='[%n@%m %1~%F{green}$(__git_ps1 " (%s)")%f]%(#.#.$) '

# Customize to your needs...

# git completion
if which brew > /dev/null 2>&1; then
  fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
fi

autoload -U compinit
compinit -u

# cdr
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':completion:*:*:cdr:*:*' menu selection
zstyle ':completion:*' recent-dirs-insert both # both | always | fallback
zstyle ':chpwd:*' recent-dirs-max 1000
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-file "${XDG_CACHE_HOME:-$HOME/.cache}/chpwd-recent-dirs"
zstyle ':chpwd:*' recent-dirs-pushd true

# peco
if which peco > /dev/null 2>&1; then
  for f ($HOME/.zsh/peco-sources/*) source "${f}"

  # keybind
  bindkey '^r' peco-select-history
  bindkey '^s' peco-ghq-look
  bindkey '^b' peco-git-branches
  bindkey '^j' peco-cdr
  # bindkey '^h' peco-ssh
fi


## direnv
if which direnv > /dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi

## composer completion
function _composer {
  # Emulate BASH's command line contents variable
  local -x COMP_LINE="$words"

  # Emulate BASH's cursor position variable, setting it to the end of the current word.
  local -x COMP_POINT
  (( COMP_POINT = ${#${(j. .)words[1,CURRENT]}} ))

  # Honour the COMPOSER_HOME variable if set
  local composer_dir=$COMPOSER_HOME
  if [ -z "$composer_dir" ]; then
    composer_dir=$HOME/.composer
  fi

  local RESULT STATUS
  local -x COMPOSER_CWD=`pwd`
  RESULT=("${(@f)$( cd $composer_dir && composer depends _completion )}")
  STATUS=$?;

  # Bail out if PHP didn't exit cleanly
  if [ $STATUS -ne 0 ]; then
    echo $RESULT;
    return $?;
  fi;

  compadd -- $RESULT
};
compdef _composer composer;

# awscli(via pip install)
[[ -s /usr/local/bin/aws_zsh_completer.sh ]] && source /usr/local/bin/aws_zsh_completer.sh

PATH="/Users/violetyk/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Users/violetyk/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/violetyk/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/violetyk/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/violetyk/perl5"; export PERL_MM_OPT;
