---
- name: brew install php
  homebrew: >
    name={{ item }}
    state=latest
  with_items:
    - php@7.1
    - composer

- name: place a profile file
  copy:
    dest: '{{ ansible_env.HOME }}/etc/profile.d/php'
    content: |
      if which brew > /dev/null 2>&1; then
        export PATH="$(brew --prefix php@7.1)/bin:$PATH"
      fi
      export PATH=$HOME/.config/composer/vendor/bin:$PATH

- name: place a fish config
  copy:
    dest: '{{ ansible_env.HOME }}/.config/fish/conf.d/php.fish'
    content: |
      if type -q brew
        set -x PATH (brew --prefix php@7.l)/bin $PATH
      end
      set -x PATH $HOME/.config/composer/vendor/bin $PATH
