---
- name: brew install
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    update_homebrew=yes
    install_options={{ item.install_options | default('') }}
  with_items:
    - cscope
    - lua
    - { name: vim,  state: head, install_options: 'with-lua,with-luajit' }

- name: set up neobundle
  file: >
    path={{ ansible_env.HOME }}/.vim/bundle
    state=directory
    recurse=yes

- name: git clone neobundle.vim
  git: >
    repo=git@github.com:Shougo/neobundle.vim
    dest={{ ansible_env.HOME }}/.vim/bundle/neobundle.vim
    accept_hostkey=yes

- name: NeoBundleInstall
  command: vim +NeoBundleInstall +q
